import type { Project } from "./types";

/**
 * Shipped as the starting portfolio. Once a database is connected these rows are
 * inserted on first boot, after which the panel is the source of truth.
 */
export const SEED_PROJECTS: Project[] = [
  {
    id: "seed-nova-studio",
    slug: "nova-studio",
    title: "Nova Studio",
    subtitle: "هویت بصری و وب‌سایت یک استودیوی خلاق",
    category: "شرکتی",
    description:
      "استودیو نوا سراغ ما آمد با یک مشکل روشن: کارشان درجه‌یک بود ولی سایتشان این را منتقل نمی‌کرد. ما از نو شروع کردیم — از هویت بصری تا آخرین پیکسل رابط کاربری. نتیجه یک تجربه تیره، سینمایی و پرکنتراست شد که کار خودِ استودیو را در مرکز توجه می‌گذارد و نه دکوراسیون اضافه را.",
    coverImage: "/placeholders/nova.png",
    gallery: ["/placeholders/luma.png", "/placeholders/vertex.png"],
    liveUrl: "https://example.com",
    client: "Nova Studio",
    year: 1403,
    duration: "۶ هفته",
    role: "طراحی برند، UI/UX، توسعه فرانت‌اند",
    tags: ["برندینگ", "UI/UX", "Next.js"],
    services: ["هویت بصری", "طراحی رابط کاربری", "توسعه فرانت‌اند"],
    results: [
      { label: "افزایش مدت ماندگاری", value: "٪۱۴۰" },
      { label: "نمره Lighthouse", value: "۹۸" },
      { label: "زمان بارگذاری", value: "۰.۹ ثانیه" },
    ],
    featured: true,
    accent: "#ff2e8b",
    sortOrder: 1,
    createdAt: new Date("2024-11-02").toISOString(),
  },
  {
    id: "seed-astra-commerce",
    slug: "astra-commerce",
    title: "Astra Commerce",
    subtitle: "فروشگاه آنلاین با تمرکز کامل روی نرخ تبدیل",
    category: "فروشگاهی",
    description:
      "آسترا یک فروشگاه پوشاک با ترافیک خوب اما نرخ تبدیل ضعیف بود. مسیر خرید را از صفر بازطراحی کردیم: جستجوی لحظه‌ای، فیلتر بدون رفرش، سبد خرید کشویی و پرداخت تک‌مرحله‌ای. سبک‌سازی سمت کلاینت باعث شد صفحات محصول زیر یک ثانیه بالا بیایند.",
    coverImage: "/placeholders/astra.png",
    gallery: ["/placeholders/luma.png", "/placeholders/vertex.png"],
    liveUrl: "https://example.com",
    client: "Astra",
    year: 1403,
    duration: "۹ هفته",
    role: "طراحی تجربه خرید، توسعه فول‌استک",
    tags: ["فروشگاهی", "React", "نرخ تبدیل"],
    services: ["طراحی تجربه کاربری", "توسعه فول‌استک", "بهینه‌سازی سرعت"],
    results: [
      { label: "رشد نرخ تبدیل", value: "٪۶۲" },
      { label: "کاهش رها کردن سبد", value: "٪۳۸" },
      { label: "سرعت صفحه محصول", value: "۰.۸ ثانیه" },
    ],
    featured: true,
    accent: "#8b5cf6",
    sortOrder: 2,
    createdAt: new Date("2024-12-18").toISOString(),
  },
  {
    id: "seed-luma-saas",
    slug: "luma-saas",
    title: "Luma SaaS",
    subtitle: "داشبورد تحلیلی برای یک پلتفرم داده",
    category: "سامانه و داشبورد",
    description:
      "لوما حجم زیادی داده داشت و هیچ راه خوبی برای خواندنش. یک سیستم طراحی کامل ساختیم — توکن‌های رنگ، مقیاس تایپوگرافی، کتابخانه نمودار — تا تیمشان بتواند بدون ما صفحه جدید بسازد. داشبورد نهایی روی داده‌های زنده و بدون کندی کار می‌کند.",
    coverImage: "/placeholders/luma.png",
    gallery: ["/placeholders/nova.png"],
    liveUrl: "https://example.com",
    client: "Luma",
    year: 1402,
    duration: "۱۲ هفته",
    role: "سیستم طراحی، معماری فرانت‌اند",
    tags: ["SaaS", "سیستم طراحی", "TypeScript"],
    services: ["سیستم طراحی", "طراحی محصول", "توسعه فرانت‌اند"],
    results: [
      { label: "سرعت ساخت صفحه جدید", value: "۳ برابر" },
      { label: "کاهش تیکت پشتیبانی", value: "٪۴۵" },
      { label: "کامپوننت قابل استفاده مجدد", value: "۶۴" },
    ],
    featured: false,
    accent: "#a855f7",
    sortOrder: 3,
    createdAt: new Date("2024-08-05").toISOString(),
  },
  {
    id: "seed-vertex-landing",
    slug: "vertex-landing",
    title: "Vertex",
    subtitle: "لندینگ محصول برای یک استارتاپ فینتک",
    category: "لندینگ",
    description:
      "ورتکس چهار هفته تا دموی سرمایه‌گذاران فاصله داشت. یک لندینگ تک‌صفحه‌ای ساختیم که محصول را در سی ثانیه توضیح می‌دهد: انیمیشن اسکرول، دمو تعاملی و یک فرم ثبت‌نام که واقعاً پر می‌شود.",
    coverImage: "/placeholders/vertex.png",
    gallery: [],
    liveUrl: "https://example.com",
    client: "Vertex",
    year: 1403,
    duration: "۴ هفته",
    role: "طراحی و توسعه",
    tags: ["لندینگ", "فینتک", "انیمیشن"],
    services: ["طراحی رابط کاربری", "توسعه فرانت‌اند"],
    results: [
      { label: "ثبت‌نام هفته اول", value: "۱۲۰۰+" },
      { label: "نرخ ثبت‌نام", value: "٪۹.۴" },
    ],
    featured: false,
    accent: "#6366f1",
    sortOrder: 4,
    createdAt: new Date("2025-01-20").toISOString(),
  },
];
